name: Debug build

on:
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Tokito-Kun/android-public-build@java17-debug
        with:
            TG_TOKEN: ${{ secrets.TG_TOKEN }}
